env:
  # id: CartPole-v1
  id: CustomCartPole-v0
  config:
    gravity: 9.8
    masscart: 1.0
    masspole: 0.1
    length: 0.5
    force_mag: 10.0
    tau: 0.02
algo:
  experiment_name: custom_cartpole/ppo
  seed: 3
  seed_in_training_env: 5
  seed_in_callback_env: 7
  train_steps: !!float 1e5
  net_arch: [256, 256]
  gamma: 0.98
  batch_size: 256
  n_steps: 32
  n_epochs: 20
  ent_coef: 0.0
  use_sde: false
  learning_rate: !!float 3e-4
  rollout_process_num: 8
  evaluate_process_num: 8
  callback_process_num: 8
  evaluate_frequence: 1000  # 多少次env.step()评估一次，如果设置为1000，且VecEnv有72个并行环境，所以实际相当于72*1000次step，评估一次
  evaluate_nums_in_evaluation: 30  # 使用evaluate_nums_in_evaluation * evaluate_process_num个episodes评估策略
  evaluate_nums_in_callback: 3  # 使用evaluate_nums_in_callback * evaluate_process_num个episodes评估策略
  save_checkpoint_every_n_timesteps: !!float 1e4
  device: cpu
