dynamics_env:
  id: CustomPendulum-v0
  params_config:
    g:
      initial_value: 10.0
      optimize: true
      range: [9.0, 10.0]
    m:
      initial_value: 1.0
      optimize: true
      range: [0.8, 1.2]
    l:
      initial_value: 1.0
      optimize: true
      range: [0.7, 1.3]
data_collected_from_real:
  obs_file_path: data/custom_pendulum/obs_real.npy
  act_file_path: data/custom_pendulum/act_real.npy
  next_obs_file_path: data/custom_pendulum/next_obs_real.npy
bo_optimizer:
  n_trials: 30
  n_jobs: -1
  sample_num_in_optimize: 1000
sys_id_env:
  reward_b: 0.2
  max_steps: 10
  loss_threshold: 1e-10
rl:
  experiment_name: sys_id/custom_pendulum/sac/g_9_5_m_0_9_l_1_2/bo_opt_step_30/seed_15
  seed: 143
  seed_in_training_env: 146
  seed_in_callback_env: 148
  net_arch: [128, 128]
  gamma: 0.95
  train_steps: !!float 1e5
  batch_size: 64
  buffer_size: !!float 1e5
  learning_starts: 100
  rollout_process_num: 1
  evaluate_process_num: 1
  callback_process_num: 1
  train_freq: 1
  gradient_steps: 1
  target_update_interval: 100
  learning_rate: !!float 3e-4
  eval_freq: !!float 1e3
  n_eval_episodes: 10
  save_checkpoint_every_n_timesteps: 20000
  device: cuda
