dynamics_env:
  id: CustomCartPole-v0
  params_config:
    gravity:
      initial_value: 10.0
      optimize: true
      range: [9.5, 10.0]
    masscart:
      initial_value: 1.0
      optimize: true
      range: [0.9, 1.1]
    masspole:
      initial_value: 0.1
      optimize: true
      range: [0.08, 0.12]
    length:
      initial_value: 0.5
      optimize: true
      range: [0.4, 0.6]
    force_mag:
      initial_value: 10.0
      optimize: true
      range: [9.0, 11.0]
    tau:
      initial_value: 0.02
      optimize: true
      range: [0.015, 0.025]
data_collected_from_real:
  obs_file_path: data/custom_cartpole/obs_real.npy
  act_file_path: data/custom_cartpole/act_real.npy
  next_obs_file_path: data/custom_cartpole/next_obs_real.npy
bo_optimizer:
  n_trials: 30
  n_jobs: -1
sys_id_env:
  reward_b: 0.2
  max_steps: 20
  loss_threshold: 1e-10
rl:
  experiment_name: sys_id/custom_cartpole/ppo/g_9_8_mc_1_0_mp_0_1_l_0_5_fm_10_0_tau_0_02/seed_1
  seed: 2
  seed_in_training_env: 3
  seed_in_callback_env: 8
  net_arch: [128, 128]
  gamma: 0.95
  train_steps: !!float 1e5
  batch_size: 64
  buffer_size: !!float 1e5
  learning_starts: 100
  rollout_process_num: 1
  evaluate_process_num: 1
  callback_process_num: 1
  train_freq: 1
  gradient_steps: 1
  target_update_interval: 100
  learning_rate: !!float 3e-4
  eval_freq: !!float 1e3
  n_eval_episodes: 5
  save_checkpoint_every_n_timesteps: 20000
  device: cuda
