dynamics_env:
  id: CustomCartPole-v0
  params_config:
    gravity:
      initial_value: 9.8
      optimize: true
      range: [9.5, 10.0]
    masscart:
      initial_value: 1.0
      optimize: true
      range: [0.8, 1.2]
    masspole:
      initial_value: 0.1
      optimize: true
      range: [0.08, 0.12]
    length:
      initial_value: 0.5
      optimize: true
      range: [0.4, 0.6]
    force_mag:
      initial_value: 10.0
      optimize: true
      range: [9.0, 11.0]
    tau:
      initial_value: 0.02
      optimize: true
      range: [0.018, 0.022]
data_collected_from_real:
  obs_file_path: data/custom_cartpole/permanent/obs_real.npy
  act_file_path: data/custom_cartpole/permanent/act_real.npy
  next_obs_file_path: data/custom_cartpole/permanent/next_obs_real.npy
bo_optimizer:
  n_trials: 30
  n_jobs: -1
  sample_num_in_optimize: 1000
sys_id_env:
  reward_b: 0.2
  max_steps: 5
  loss_threshold: 1e-10
rl:
  experiment_name: sys_id/custom_cartpole/ppo/g_9_8_mc_1_1_mp_0_09_l_0_55_fm_10_0_tau_0_02/bo_opt_step_30/seed_3
  seed: 23
  seed_in_training_env: 26
  seed_in_callback_env: 29
  net_arch: [128, 128]
  gamma: 0.9
  train_steps: !!float 1e5
  batch_size: 64
  buffer_size: !!float 1e5
  learning_starts: 100
  rollout_process_num: 1
  evaluate_process_num: 1
  callback_process_num: 1
  train_freq: 1
  gradient_steps: 1
  target_update_interval: 100
  learning_rate: !!float 3e-4
  eval_freq: !!float 1e3
  n_eval_episodes: 10
  save_checkpoint_every_n_timesteps: 20000
  device: cuda
